[project]
name = "ragsystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cairosvg>=2.9.0",
    "chromadb>=1.5.9",
    "datasets>=4.8.4",
    "faiss-cpu>=1.13.2",
    "google-genai>=1.73.1",
    "ipython>=9.13.0",
    "jsonref>=1.1.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-experimental>=0.4.1",
    "langchain-google-genai>=4.2.2",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.1",
    "langchain-unstructured>=1.0.1",
    "litellm>=1.83.10",
    "markdown-it-py>=4.0.0",
    "nltk>=3.9.4",
    "numpy>=2.4.4",
    "ollama>=0.6.1",
    "openai>=2.24.0",
    "pageindex>=0.2.8",
    "pandas>=3.0.2",
    "pdfplumber>=0.11.9",
    "pymupdf4llm>=1.27.2.3",
    "pypdf>=6.10.2",
    "pypdf2>=3.0.1",
    "pyyaml>=6.0.3",
    "ragas>=0.4.3",
    "rank-bm25>=0.2.2",
    "rapidfuzz>=3.14.5",
    "sentence-transformers>=5.4.1",
    "tabulate>=0.10.0",
    "torch>=2.11.0",
    "tqdm>=4.67.3",
    "transformers>=5.7.0",
    "unstructured[pdf]>=0.24.1",
]
